#!/bin/sh -e
#
# /etc/init.d/avrecord: Start avrecord
#
### BEGIN INIT INFO
# Provides:	     avrecord
# Required-Start:    $local_fs $syslog $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start avrecord
# Description:       starts avrecord and assigns privileges
### END INIT INFO

# Ported to new debian way using sh and /lib/lsb/init-functions
# by Angel Carpintero <ack@telefonica.net>
# Modified by : Juan Angulo Moreno <juan@apuntale.com>
#               Eddy Petrisor <eddy.petrisor@gmail.com>
#               ArAge <ArAge@gmx.co.uk>
#               Allis Tauri <allista@gmail.com>

# To enable run: 
#	sudo update-rc.d avrecord defaults 99
# Note, that running avrecord with 99 priority
# ensures that sound devices were already initialized

NAME=avrecord
PATH_BIN=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
DEFAULTS=/etc/default/$NAME
CONFIG=/etc/$NAME/avrecord.cfg
DESC="Audio-Video recorder with motion and noise detection daemon"

ENV="env -i LANG=C PATH=$PATH_BIN MALLOC_CHECK_=1"

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

RET=0

[ -r "$DEFAULTS" ] && . "$DEFAULTS" || start_avrecord=yes

wait_for_snd_devices () {
    # without this avrecord cannot open "default" alsa device
    while [ ! -d /dev/snd/by-path ]; do sleep 1; done;
}

check_daemon_enabled () {
    if [ "$start_avrecord" = "yes" ] ; then
        return 0
    else
        log_warning_msg "Not starting $NAME daemon, disabled via /etc/default/$NAME"
        return 1
    fi

}


case "$1" in
  start)
    if check_daemon_enabled ; then
        if ! [ -f $PIDFILE ]; then
            touch $PIDFILE
        fi
        chown $NAME:$NAME $PIDFILE
        
        log_daemon_msg "Starting $DESC"
	wait_for_snd_devices
        if start-stop-daemon --start --oknodo --chuid $NAME --group $NAME --pidfile $PIDFILE --exec $DAEMON -- -d -c $CONFIG -p $PIDFILE; then
            log_end_msg 0
        else
            log_end_msg 1
            RET=1
        fi
    fi
    ;;

  stop)
    log_daemon_msg "Stopping $DESC"
    if start-stop-daemon --stop --oknodo --exec $DAEMON --retry 30 ; then
        log_end_msg 0
    else
        log_end_msg 1
        RET=1
    fi
    ;;

  reload|force-reload)
    log_daemon_msg "Reloading $NAME configuration"
    if start-stop-daemon --stop --signal HUP --exec $DAEMON ; then
        log_end_msg 0
    else
        log_end_msg 1
        RET=1
    fi
    ;;

  restart)
    if check_daemon_enabled ; then
        log_action_begin_msg "Restarting $NAME"
        if $0 stop && $0 start ; then
            log_action_end_msg 0
        else
            log_action_cont_msg "(failed)"
            RET=1
        fi
    fi
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload}"
    RET=1
    ;;
esac


exit $RET
